{
    'id': '165255', 
    'branch_id': '1', 
    'regular': 0, 
    'from_regular': 1, 
    'type': '2', 
    'icon': 'ion-person-stalker', 
    'status': '1', 
    'room': '-1', 
    'room_s': '', 
    'location_id': None, 
    'sorting': '999999', 
    'class': 'type2 status1 room-1', 
    'title': 'ПМП 107 (4)', 
    'teacher_id': '71', 
    'teacher': 'Бутаков Лев Юрьевич', 
    'subject': 'Python. Уровень 2 гр ПРЕМИУМ', 
    'subject_id': 41, 
    'customers': {
        '6774': 'Джабраил Таибов', 
        '2018': 'Иван Сафронов MAX', 
        '6533': 'Ксения Баннова', 
        '2071': 'Сергей Духин МАХ'}, 
    'start': '2026-07-17 20:00:01', 'end': '2026-07-17 21:00:00', 
    'duration': 60, 'date': '2026-07-17', 
    'note': '', 'is_public': 0, 
    'limit': None, 
    'enrolled': 4, 
    'searchbuf': 'Бутаков Лев Юрьевич Джабраил Таибов  Иван Сафронов MAX  Ксения Баннова  Сергей Духин МАХ  Python. Уровень 2 гр ПРЕМИУМ ПМП 107 ', 
    'homework': None, 
    'topic': '', 
    'is_available_for_enroll': False}